import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";

import "./globals.css";

import { ThemeProvider } from "@/components/ThemeProvider";
import { BackgroundGradientAnimation } from "@/components/ui/background-gradient-animation";
import { TRPCProvider } from "@/app/_trpc/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TRPCProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            forcedTheme="dark"
          >
            {/* Container หลัก */}
            <div className="relative min-h-screen flex flex-col justify-between bg-blue-600/20 px-4 pb-2 pt-2">
              <BackgroundGradientAnimation />

              <div className="flex-1 z-10">{children}</div>

              <div className="flex justify-center z-10">
                <Image
                  width={140}
                  height={60}
                  alt="TPE Logo"
                  src="/assets/TPE-Logo.png"
                  className="sm:w-[160px] md:w-[200px] h-auto"
                />
              </div>
            </div>
          </ThemeProvider>
        </TRPCProvider>
      </body>
    </html>
  );
}
